# -*- coding: utf-8 -*-
"""Chapter1_Exercise 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bec_0ZD1H2ZPQ2ma_CS7JmhAexez7HMC
"""

import datetime
now = datetime.datetime.now()
print("Current date and time:")
print(now.strftime("%Y-%m-%d %H:%M:%S"))