# -*- coding: utf-8 -*-
"""Chapter1_Exercise 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rN-HUvQDxSjCR-yNUitmOTVhiTdiYN-X
"""

import sys
print("Python version")
print(sys.version)
print("version info.")
print(sys.version_info)