# -*- coding: utf-8 -*-
"""Chapter 1 exercises

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/aysha05118/f1ac59c1133c3d3322a9e0198ff060e3/untitled1.ipynb
"""

print("Twinkle,twinkle, little star, How i wonder what you are! Up above the world so high, Like a diamond in the sky. Twinkle, twinkle, little star, How i wonder what you are")

import sys
print("Python version")
print(sys.version)
print("version info.")
print(sys.version_info)

import datetime
now = datetime.datetime.now()
print("Current date and time:")
print(now.strftime("%Y-%m-%d %H:%M:%S"))

a = " python"
b = " is"
c = " cool"
print(a+b+c)

from math import pi
r = float(input("input the radius of the circle:"))
print("The area of the circle with radius " + str(r) + "is:" + str(pi * r**2))