# -*- coding: utf-8 -*-
"""Chapter1_Exercise 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qZqtPmfHWMlyNf9QJSPPop3giIkgCB5A
"""

from math import pi
r = float(input("input the radius of the circle:"))
print("The area of the circle with radius " + str(r) + "is:" + str(pi * r**2))