# -*- coding: utf-8 -*-
"""Chapter1_Exercise 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8XW2MpK9uIlkZgB7Im1c5ZJtnTCj3r_
"""

a = " python"
b = " is"
c = " cool"
print(a+b+c)