# -*- coding: utf-8 -*-
"""Chapter1_Exercise 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/aysha05118/f1ac59c1133c3d3322a9e0198ff060e3/untitled1.ipynb
"""

print("Twinkle,twinkle, little star, How i wonder what you are! Up above the world so high, Like a diamond in the sky. Twinkle, twinkle, little star, How i wonder what you are")